### ISSUE TITLE
Ocean Post Slider 2.0.0

### ISSUE THREAD

**Issue by carosouza** [oceanwp/ocean-posts-slider#1]
Hi there was an update today, and version 2.0.0 does not have 3 images per slide as configured and does not run the slider for the next image. Previous version 1.1.1 works fine. Only 1 image per slide.
![post-slider-1](https://user-images.githubusercontent.com/1892405/126344061-0c9ed60b-4a51-4fe1-aa79-a878c4cec65b.png)
![post-slider-2](https://user-images.githubusercontent.com/1892405/126344067-01ec8cf0-2af0-45fd-b28f-341c54cb277b.png)

**Comment by MarkHollo** [comment]
Hello @carosouza,

We'll be releasing the 2.0.1 version today. After you update and made sure all caching is purged, let us know if you're still experiencing problems on your end.

Thank you

**Comment by MarkHollo** [comment]
I'm closing this thread because the issue has been claimed as resolved by users who experienced the same problem. If you continue to experience this or any other problem, feel free to reopen it or start a new thread.

Thank you and wishing you an amazing day

**Comment by carosouza** [comment]
Thanks!
